{% set name = "suitcase-msgpack" %}
{% set version = "0.3.0" %}
{% set sha256 = "f846a7b63ae2d7676787f5269ca2bdd3c33532fc80608499c696752628cd4e5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python
    - pip
  run:
    - python
    - event-model >=1.8.0
    - msgpack-numpy
    - msgpack-python
    - suitcase-utils

test:
  imports:
    - suitcase.msgpack

about:
  home: https://blueskyproject.io/suitcase
  license: BSD (3-clause)
  license_family: BSD
  license_file: LICENSE
  summary: Export bluesky documents to msgpack
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-msgpack
